# -*- coding: utf-8 -*-
"""Analisis_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DD2DYNuCgQ6UO-gyv28OeAocfmw0TSqf
"""

import os
import glob
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

base_dir = "/content/drive/MyDrive/IA 1/Proyecto/DataSets/Dataset - Landslide4Sense/TrainData"

# Configuración visual
sns.set_theme(style="whitegrid", context="talk")
sns.set_palette(sns.color_palette(["#2ecc71", "#e74c3c"])) # Verde (0: Fondo) | Rojo (1: Deslizamiento)

img_dir = os.path.join(base_dir, "img")
mask_dir = os.path.join(base_dir, "mask")

img_files = sorted(glob.glob(os.path.join(img_dir, "**", "*.h5"), recursive=True))
if not img_files:
    img_files = sorted(glob.glob(os.path.join(img_dir, "*.h5")))

if not img_files:
    raise FileNotFoundError(f"No se encontraron archivos .h5 en {img_dir}")

print(f"Éxito: Se localizaron {len(img_files)} imágenes .h5")

pixels_fondo = 0
pixels_deslizamiento = 0
datos_espectrales = []
datos_topograficos = []
datos_ndvi = []
sample_pixels = []

muestras_a_procesar = min(50, len(img_files))

for img_path in img_files[:muestras_a_procesar]:
    nombre_img = os.path.basename(img_path)
    nombre_mask = nombre_img.replace("image_", "mask_")
    mask_path = os.path.join(mask_dir, nombre_mask)

    if not os.path.exists(mask_path):
        continue

    with h5py.File(img_path, 'r') as hf_img, h5py.File(mask_path, 'r') as hf_mask:
        img = np.array(hf_img['img'])
        mask = np.array(hf_mask['mask']).flatten()

        if img.ndim == 3 and img.shape[0] == 14:
            img = np.transpose(img, (1, 2, 0))

        flat_img = img.reshape(-1, 14)

        # Conteo para desbalance de clases
        pixels_deslizamiento += int(np.sum(mask == 1))
        pixels_fondo += int(np.sum(mask == 0))


        b4 = flat_img[:, 3]
        b8 = flat_img[:, 7]
        ndvi = np.nan_to_num((b8 - b4) / (b8 + b4 + 1e-8))


        combined = np.column_stack((flat_img, ndvi, mask))


        idx_0 = np.where(mask == 0)[0]
        idx_1 = np.where(mask == 1)[0]

        valid_subs = []
        if len(idx_0) > 0:
            valid_subs.append(np.random.choice(idx_0, min(150, len(idx_0)), replace=False))
        if len(idx_1) > 0:
            valid_subs.append(np.random.choice(idx_1, min(150, len(idx_1)), replace=False))

        if valid_subs:
            sub_indices = np.concatenate(valid_subs).astype(int)
            sample_pixels.append(combined[sub_indices, :])


        for c_val, c_name in zip([0, 1], ['Fondo', 'Deslizamiento']):
            idxs = np.where(mask == c_val)[0]
            if len(idxs) > 0:
                sub = np.random.choice(idxs, min(100, len(idxs)), replace=False)

                for val in ndvi[sub]:
                    datos_ndvi.append({'NDVI': val, 'Clase': c_name})

                sub_espectral = flat_img[sub, :12]
                for b_idx in range(12):
                    for val in sub_espectral[:, b_idx]:
                        datos_espectrales.append({
                            'Banda': f'B{b_idx+1}',
                            'Reflectancia': val,
                            'Clase': c_name
                        })

                for elev, pend in zip(flat_img[sub, 12], flat_img[sub, 13]):
                    datos_topograficos.append({
                        'Elevación (DEM)': elev,
                        'Pendiente (Slope)': pend,
                        'Clase': c_name
                    })

# Creación de DataFrames
df_ndvi = pd.DataFrame(datos_ndvi)
df_espectral = pd.DataFrame(datos_espectrales)
df_topo = pd.DataFrame(datos_topograficos)

corr_cols = [f'B{i+1}' for i in range(12)] + ['DEM', 'Slope', 'NDVI', 'Mask']
if sample_pixels:
    df_corr = pd.DataFrame(np.vstack(sample_pixels), columns=corr_cols)
else:
    df_corr = pd.DataFrame(columns=corr_cols)


# Gráfico 1: Desbalance de Clases
plt.figure(figsize=(7, 5))
total_pixels = pixels_fondo + pixels_deslizamiento
if total_pixels > 0:
    pcts = [(pixels_fondo / total_pixels) * 100, (pixels_deslizamiento / total_pixels) * 100]
    ax = sns.barplot(x=['Fondo (0)', 'Deslizamiento (1)'], y=pcts, hue=['Fondo (0)', 'Deslizamiento (1)'], legend=False)
    plt.title('Distribución de Píxeles (Desbalance de Clases)', fontweight='bold')
    plt.ylabel('Porcentaje (%)')
    for p in ax.patches:
        ax.annotate(f'{p.get_height():.2f}%', (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha='center', va='bottom', fontsize=11, fontweight='bold', xytext=(0, 5), textcoords='offset points')
    plt.tight_layout()
    plt.show()

# Gráfico 2: Firma Espectral Promedio
if not df_espectral.empty:
    plt.figure(figsize=(11, 5))
    sns.lineplot(data=df_espectral, x='Banda', y='Reflectancia', hue='Clase', marker="o", errorbar=None, linewidth=2.5)
    plt.title('Firma Espectral Promedio: Fondo vs. Deslizamiento', fontweight='bold')
    plt.xlabel('Bandas Espectrales (B1-B12)')
    plt.ylabel('Reflectancia')
    plt.tight_layout()
    plt.show()

# Gráfico 3: Distribución de Pendiente (KDE Plot)
if not df_topo.empty:
    plt.figure(figsize=(9, 5))
    sns.kdeplot(data=df_topo, x='Pendiente (Slope)', hue='Clase', fill=True, common_norm=False, alpha=0.5, linewidth=2)
    plt.title('Distribución de Pendiente del Terreno (Banda 14)', fontweight='bold')
    plt.xlabel('Grados / Valor de Pendiente')
    plt.ylabel('Densidad')
    plt.tight_layout()
    plt.show()

# Gráfico 4: Distribución de NDVI (Boxplot)
if not df_ndvi.empty:
    plt.figure(figsize=(8, 5))
    sns.boxplot(data=df_ndvi, x='Clase', y='NDVI', hue='Clase', showfliers=False, legend=False)
    plt.title('Distribución de NDVI: Vegetación vs. Deslizamiento', fontweight='bold')
    plt.ylabel('Índice NDVI')
    plt.tight_layout()
    plt.show()

# Gráfico 5: Matriz de Correlación
if not df_corr.empty:
    plt.figure(figsize=(14, 11))
    corr = df_corr.corr()
    mask_tri = np.triu(np.ones_like(corr, dtype=bool), k=1)

    sns.heatmap(
        corr,
        mask=mask_tri,
        annot=True,
        fmt=".2f",
        cmap='coolwarm',
        vmin=-1,
        vmax=1,
        linewidths=0.5,
        annot_kws={"size": 9},
        cbar_kws={"shrink": 0.8}
    )
    plt.title('Matriz de Correlación', fontweight='bold', fontsize=14)
    plt.tight_layout()
    plt.show()

# Gráfico 6: Muestra Integrada Espacial (2x2)
for img_path in img_files:
    nombre_mask = os.path.basename(img_path).replace("image_", "mask_")
    mask_path = os.path.join(mask_dir, nombre_mask)
    if not os.path.exists(mask_path):
        continue

    with h5py.File(img_path, 'r') as hf_img, h5py.File(mask_path, 'r') as hf_mask:
        mask_map = np.array(hf_mask['mask'])
        if np.sum(mask_map == 1) > 300:
            img_map = np.array(hf_img['img'])
            if img_map.ndim == 3 and img_map.shape[0] == 14:
                img_map = np.transpose(img_map, (1, 2, 0))

            rgb = img_map[:, :, [3, 2, 1]].astype(float)
            for i in range(3):
                p2, p98 = np.percentile(rgb[:, :, i], (2, 98))
                rgb[:, :, i] = np.clip((rgb[:, :, i] - p2) / (p98 - p2 + 1e-8), 0, 1)

            b4, b8 = img_map[:, :, 3], img_map[:, :, 7]
            ndvi_map = np.nan_to_num((b8 - b4) / (b8 + b4 + 1e-8))

            fig, axes = plt.subplots(2, 2, figsize=(10, 10))
            axes[0, 0].imshow(rgb)
            axes[0, 0].set_title('Color Real (RGB)')
            axes[0, 0].axis('off')

            axes[0, 1].imshow(mask_map, cmap='Reds')
            axes[0, 1].set_title('Máscara Ground Truth (Mask)')
            axes[0, 1].axis('off')

            im_ndvi = axes[1, 0].imshow(ndvi_map, cmap='YlGn')
            axes[1, 0].set_title('Mapa de NDVI')
            axes[1, 0].axis('off')
            plt.colorbar(im_ndvi, ax=axes[1, 0], fraction=0.046)

            im_slope = axes[1, 1].imshow(img_map[:, :, 13], cmap='magma')
            axes[1, 1].set_title('Pendiente (Slope)')
            axes[1, 1].axis('off')
            plt.colorbar(im_slope, ax=axes[1, 1], fraction=0.046)

            plt.suptitle('Análisis Espacial Integrado de Muestra Seleccionada', fontweight='bold', fontsize=16)
            plt.tight_layout()
            plt.show()
            break